//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashtag.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ashtag.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AshTag is a rapidly-built app aimed at helping to identify and report incidences of the Ash dieback fungus, or Chalara fraxinea. The project is being led by the University of East Anglia&apos;s Adapt Group, and has the support of most key forestry and wildlife agencies. Latest info at www.ashtag.org.  Please use the identification gallery images to spot telltale signs of the fungus. If you believe you have a suspicious sighting, use the app to take a close up photo of the symptom which most matches the identific [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPageContent {
            get {
                return ResourceManager.GetString("AboutPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageHeader {
            get {
                return ResourceManager.GetString("AboutPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASHTAG.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ias-ess.org/api.
        /// </summary>
        public static string BaseUri_AppSetting {
            get {
                return ResourceManager.GetString("BaseUri_AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id guide.
        /// </summary>
        public static string IdGuidePageHeader {
            get {
                return ResourceManager.GetString("IdGuidePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step one: Make sure it is an Ash tree.
        /// </summary>
        public static string IdGuidePageStep1 {
            get {
                return ResourceManager.GetString("IdGuidePageStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step two: Make sure it is an Ash tree and also this has some really long text.
        /// </summary>
        public static string IdGuidePageStep2 {
            get {
                return ResourceManager.GetString("IdGuidePageStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step three: Make sure it is an Ash tree.
        /// </summary>
        public static string IdGuidePageStep3 {
            get {
                return ResourceManager.GetString("IdGuidePageStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step four: Make sure it is an Ash tree.
        /// </summary>
        public static string IdGuidePageStep4 {
            get {
                return ResourceManager.GetString("IdGuidePageStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step five: Make sure it is an Ash tree.
        /// </summary>
        public static string IdGuidePageStep5 {
            get {
                return ResourceManager.GetString("IdGuidePageStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email address.
        /// </summary>
        public static string MainPage_EmptyEmailAddressMessageBoxCaption {
            get {
                return ResourceManager.GetString("MainPage_EmptyEmailAddressMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address to submit a sighting.
        /// </summary>
        public static string MainPage_EmptyEmailAddressMessageBoxText {
            get {
                return ResourceManager.GetString("MainPage_EmptyEmailAddressMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string MainPageEmailAddressLabel {
            get {
                return ResourceManager.GetString("MainPageEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string MainPageHeader {
            get {
                return ResourceManager.GetString("MainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AshTag is a free tool to help you do your bit to track the spread of the Ash ‘die back’ fungus and limit its impact..
        /// </summary>
        public static string MainPageIntroduction {
            get {
                return ResourceManager.GetString("MainPageIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take picture.
        /// </summary>
        public static string SelectImagePageTakePictureButton {
            get {
                return ResourceManager.GetString("SelectImagePageTakePictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select image.
        /// </summary>
        public static string SelectImagePageTitle {
            get {
                return ResourceManager.GetString("SelectImagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set location.
        /// </summary>
        public static string SetLocationPageTitle {
            get {
                return ResourceManager.GetString("SetLocationPageTitle", resourceCulture);
            }
        }
    }
}
